# resources below create influxdb resources and they are
# designed in this particular way for RBAC management

# Config CR defines how to reach influxdb service running
# in a namespace along with api token. In other words,
# Config CR defines things to instantiate influxdb2 api client.

# Organization CR and Token CR create respective resources,
# and they can do so via influxdb2 client instantiated via
# Config CR that can be defined in the spec. This allows
# RBAC to be permissive for these resources and restrictive
# for Bucket CR

# Bucket CR, on the other hand, does not have an ability to
# reference a Config CR and always assumes presence of a
# Config CR named default.

# config below is used by the organization CR to create new organizations
apiVersion: influxdb.kubetrail.io/v1beta1
kind: Config
metadata:
  name: config-for-org-crud               # (1) this can be referenced in organization cr
spec:
  orgName: influxdata
  tokenSecretName: influxdata-admin-token
  tokenSecretNamespace: influxdb2-system
---
apiVersion: influxdb.kubetrail.io/v1beta1
kind: Organization
metadata:
  name: sample-organization               # (2) org name to create
spec:
  configName: config-for-org-crud         # (1) reference config created earlier to access admin token
---
# config below is used by the token CR to create new tokens
apiVersion: influxdb.kubetrail.io/v1beta1
kind: Config
metadata:
  name: config-for-token-crud            # (3) config name to reference in token creation cr
spec:
  orgName: sample-organization           # (2) reference to org name created above
  tokenSecretName: influxdata-admin-token
  tokenSecretNamespace: influxdb2-system
---
apiVersion: influxdb.kubetrail.io/v1beta1
kind: Token
metadata:
  name: organization-admin-token
spec:
  configName: config-for-token-crud       # (3) refer to the config created above to access admin token
  secretName: organization-admin-token    # (4) secret name to write token to in self ns
  permissions:
    - permissionType: write
      resourceType: orgs
    - permissionType: read
      resourceType: orgs
    - permissionType: write
      resourceType: buckets
    - permissionType: read
      resourceType: buckets
---
# config below is used to create new buckets
apiVersion: influxdb.kubetrail.io/v1beta1
kind: Config
metadata:
  name: default                              # (5) bucket cr ALWAYS works via default config
spec:
  orgName: sample-organization               # (2) organization to operate in
  tokenSecretName: organization-admin-token  # (4) secret name created above
---
apiVersion: influxdb.kubetrail.io/v1beta1
kind: Bucket
metadata:
  name: sample-bucket                        # (6) name of bucket to create... always via default config (5)
spec:
  secondsTtl: 0 # or >= 3600
  description: bucket to store sensor data
