apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-operator-controller-manager
  namespace: influxdb-operator-system
spec:
  template:
    spec:
      imagePullSecrets:
        - name: artifact-registry-key
